# Generated by Django 4.1 on 2022-08-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalwebsiteapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmodel',
            name='hiring',
            field=models.BooleanField(verbose_name=False),
        ),
        migrations.AlterField(
            model_name='formmodel',
            name='ok_to_contact',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
