# Generated by Django 4.1 on 2022-08-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalwebsiteapi', '0004_formmodel_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='email',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
