# Generated by Django 4.1 on 2022-08-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalwebsiteapi', '0007_remove_formmodel_user_formmodel_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='member',
        ),
    ]
