# Generated by Django 4.1 on 2022-08-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalwebsiteapi', '0008_remove_formmodel_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='industry',
        ),
    ]
